import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";

export type User = { id:string; name:string; email:string; passwordHash:string; createdAt:string };
export type Note = { id:string; ownerId:string; title:string; content:string; createdAt:string };
export type Share = { id:string; noteId:string; token:string; accessType:"public"|"password"; shareType:"one-time"|"time-based"; expiryAt:string|null; accessKeyHash:string|null; accessKeyHint:string|null; usedAt:string|null; revokedAt:string|null; viewCount:number; createdAt:string };
type State = { users:User[]; notes:Note[]; shares:Share[]; sessions:{token:string; userId:string; createdAt:string}[] };
const file = path.join(process.cwd(), ".data", "store.json");
let queue = Promise.resolve();
const blank = ():State => ({users:[],notes:[],shares:[],sessions:[]});
function load():State { try { return JSON.parse(fs.readFileSync(file,"utf8")); } catch { return blank(); } }
function save(s:State) { fs.mkdirSync(path.dirname(file),{recursive:true}); fs.writeFileSync(file, JSON.stringify(s,null,2)); }
async function tx<T>(fn:(s:State)=>T|Promise<T>):Promise<T> { const run = queue.then(async()=>{const s=load(); const out=await fn(s); save(s); return out;}); queue=run.then(()=>undefined,()=>undefined); return run; }
function hash(password:string, salt=crypto.randomBytes(16).toString("hex")) { return `${salt}:${crypto.scryptSync(password,salt,32).toString("hex")}`; }
function matches(password:string, stored:string) { const [salt,hex]=stored.split(":"); if(!salt||!hex) return false; const a=Buffer.from(hex,"hex"); const b=crypto.scryptSync(password,salt,32); return a.length===b.length&&crypto.timingSafeEqual(a,b); }
const id=()=>crypto.randomUUID();
export async function register(name:string,email:string,password:string) { return tx(s=>{ if(s.users.some(u=>u.email.toLowerCase()===email.toLowerCase())) throw new Error("Email already registered"); const user={id:id(),name,email:email.toLowerCase(),passwordHash:hash(password),createdAt:new Date().toISOString()}; s.users.push(user); const token=id(); s.sessions.push({token,userId:user.id,createdAt:new Date().toISOString()}); return {user:{id:user.id,name:user.name,email:user.email},token}; }); }
export async function login(email:string,password:string) { return tx(s=>{const user=s.users.find(u=>u.email===email.toLowerCase()); if(!user||!matches(password,user.passwordHash)) throw new Error("Invalid email or password"); const token=id(); s.sessions.push({token,userId:user.id,createdAt:new Date().toISOString()}); return {user:{id:user.id,name:user.name,email:user.email},token}; }); }
export async function userForToken(token:string|undefined) { if(!token)return null; const s=load(); const session=s.sessions.find(x=>x.token===token); const u=session&&s.users.find(x=>x.id===session.userId); return u?{id:u.id,name:u.name,email:u.email}:null; }
export async function createNote(ownerId:string,title:string,content:string,opts:{accessType:"public"|"password";shareType:"one-time"|"time-based";expiryAt:string|null}) { return tx(s=>{const note:Note={id:id(),ownerId,title,content,createdAt:new Date().toISOString()}; const token=crypto.randomBytes(24).toString("base64url"); const accessKey=opts.accessType==="password"?crypto.randomBytes(8).toString("base64url"):null; const share:Share={id:id(),noteId:note.id,token,accessType:opts.accessType,shareType:opts.shareType,expiryAt:opts.shareType==="time-based"?opts.expiryAt:null,accessKeyHash:accessKey?hash(accessKey):null,accessKeyHint:accessKey?`${accessKey.slice(0,3)}•••`:null,usedAt:null,revokedAt:null,viewCount:0,createdAt:new Date().toISOString()}; s.notes.push(note);s.shares.push(share); return {note,share,accessKey}; }); }
export async function notesFor(ownerId:string) { const s=load(); return s.notes.filter(n=>n.ownerId===ownerId).map(note=>({note,shares:s.shares.filter(x=>x.noteId===note.id)})); }
export async function noteFor(ownerId:string,noteId:string) { const s=load(); const note=s.notes.find(n=>n.id===noteId&&n.ownerId===ownerId); return note?{note,shares:s.shares.filter(x=>x.noteId===note.id)}:null; }
export async function revokeShare(ownerId:string,token:string) { return tx(s=>{const share=s.shares.find(x=>x.token===token); const note=share&&s.notes.find(n=>n.id===share.noteId&&n.ownerId===ownerId); if(!share||!note) throw new Error("Share not found"); share.revokedAt=new Date().toISOString(); return share;}); }
export async function accessShare(token:string,password?:string) { return tx(s=>{const share=s.shares.find(x=>x.token===token); const note=share&&s.notes.find(n=>n.id===share.noteId); if(!share||!note) return {status:404 as const,error:"Invalid share link"}; if(share.revokedAt) return {status:410 as const,error:"This link was revoked"}; if(share.expiryAt&&new Date(share.expiryAt).getTime()<=Date.now()) return {status:410 as const,error:"This link has expired"}; if(share.accessType==="password"&&(!password||!share.accessKeyHash||!matches(password,share.accessKeyHash))) return {status:401 as const,error:"Incorrect password/key"}; if(share.shareType==="one-time"&&share.usedAt) return {status:410 as const,error:"This one-time link was already used"}; share.viewCount+=1; if(share.shareType==="one-time") share.usedAt=new Date().toISOString(); return {status:200 as const,note:{title:note.title,content:note.content},share:{accessType:share.accessType,shareType:share.shareType,viewCount:share.viewCount,expiryAt:share.expiryAt}}; }); }
